//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2015-01-09 17:44:20
namespace KendoUI.Models.OData.Models
{
    /// <summary>
    /// There are no comments for CategorySingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("CategorySingle")]
    public partial class CategorySingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Category>
    {
        /// <summary>
        /// Initialize a new CategorySingle object.
        /// </summary>
        public CategorySingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new CategorySingle object.
        /// </summary>
        public CategorySingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}
    }
    /// <summary>
    /// There are no comments for Category in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("ID")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Category")]
    public partial class Category : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        public static Category CreateCategory(int ID, string name)
        {
            Category category = new Category();
            category.ID = ID;
            category.Name = name;
            return category;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ID")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ProductSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ProductSingle")]
    public partial class ProductSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Product>
    {
        /// <summary>
        /// Initialize a new ProductSingle object.
        /// </summary>
        public ProductSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ProductSingle object.
        /// </summary>
        public ProductSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}
        /// <summary>
        /// There are no comments for Category in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        public global::KendoUI.Models.OData.Models.CategorySingle Category
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Category == null))
                {
                    this._Category = new global::KendoUI.Models.OData.Models.CategorySingle(this.Context, GetPath("Category"));
                }
                return this._Category;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::KendoUI.Models.OData.Models.CategorySingle _Category;
    }
    /// <summary>
    /// There are no comments for Product in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("ID")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Product")]
    public partial class Product : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        public static Product CreateProduct(global::System.Guid ID, string name)
        {
            Product product = new Product();
            product.ID = ID;
            product.Name = name;
            return product;
        }
        /// <summary>
        /// There are no comments for Property UnitPrice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("UnitPrice")]
        public global::System.Nullable<decimal> UnitPrice
        {
            get
            {
                return this._UnitPrice;
            }
            set
            {
                this.OnUnitPriceChanging(value);
                this._UnitPrice = value;
                this.OnUnitPriceChanged();
                this.OnPropertyChanged("UnitPrice");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::System.Nullable<decimal> _UnitPrice;
        partial void OnUnitPriceChanging(global::System.Nullable<decimal> value);
        partial void OnUnitPriceChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Date")]
        public global::System.Nullable<global::System.DateTimeOffset> Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
                this.OnPropertyChanged("Date");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Date;
        partial void OnDateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDateChanged();
        /// <summary>
        /// There are no comments for Property SmallDateTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("SmallDateTime")]
        public global::System.Nullable<global::System.DateTimeOffset> SmallDateTime
        {
            get
            {
                return this._SmallDateTime;
            }
            set
            {
                this.OnSmallDateTimeChanging(value);
                this._SmallDateTime = value;
                this.OnSmallDateTimeChanged();
                this.OnPropertyChanged("SmallDateTime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _SmallDateTime;
        partial void OnSmallDateTimeChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnSmallDateTimeChanged();
        /// <summary>
        /// There are no comments for Property DateTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DateTime")]
        public global::System.Nullable<global::System.DateTimeOffset> DateTime
        {
            get
            {
                return this._DateTime;
            }
            set
            {
                this.OnDateTimeChanging(value);
                this._DateTime = value;
                this.OnDateTimeChanged();
                this.OnPropertyChanged("DateTime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _DateTime;
        partial void OnDateTimeChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDateTimeChanged();
        /// <summary>
        /// There are no comments for Property DateTime2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DateTime2")]
        public global::System.Nullable<global::System.DateTimeOffset> DateTime2
        {
            get
            {
                return this._DateTime2;
            }
            set
            {
                this.OnDateTime2Changing(value);
                this._DateTime2 = value;
                this.OnDateTime2Changed();
                this.OnPropertyChanged("DateTime2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _DateTime2;
        partial void OnDateTime2Changing(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDateTime2Changed();
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ID")]
        public global::System.Guid ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property CurrencyID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CurrencyID")]
        public global::System.Nullable<short> CurrencyID
        {
            get
            {
                return this._CurrencyID;
            }
            set
            {
                this.OnCurrencyIDChanging(value);
                this._CurrencyID = value;
                this.OnCurrencyIDChanged();
                this.OnPropertyChanged("CurrencyID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::System.Nullable<short> _CurrencyID;
        partial void OnCurrencyIDChanging(global::System.Nullable<short> value);
        partial void OnCurrencyIDChanged();
        /// <summary>
        /// There are no comments for Property CategoryID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CategoryID")]
        public global::System.Nullable<int> CategoryID
        {
            get
            {
                return this._CategoryID;
            }
            set
            {
                this.OnCategoryIDChanging(value);
                this._CategoryID = value;
                this.OnCategoryIDChanged();
                this.OnPropertyChanged("CategoryID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::System.Nullable<int> _CategoryID;
        partial void OnCategoryIDChanging(global::System.Nullable<int> value);
        partial void OnCategoryIDChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Description")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property IntroductionUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IntroductionUrl")]
        public string IntroductionUrl
        {
            get
            {
                return this._IntroductionUrl;
            }
            set
            {
                this.OnIntroductionUrlChanging(value);
                this._IntroductionUrl = value;
                this.OnIntroductionUrlChanged();
                this.OnPropertyChanged("IntroductionUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private string _IntroductionUrl;
        partial void OnIntroductionUrlChanging(string value);
        partial void OnIntroductionUrlChanged();
        /// <summary>
        /// There are no comments for Property ImageUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ImageUrl")]
        public string ImageUrl
        {
            get
            {
                return this._ImageUrl;
            }
            set
            {
                this.OnImageUrlChanging(value);
                this._ImageUrl = value;
                this.OnImageUrlChanged();
                this.OnPropertyChanged("ImageUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private string _ImageUrl;
        partial void OnImageUrlChanging(string value);
        partial void OnImageUrlChanged();
        /// <summary>
        /// There are no comments for Property Memo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Memo")]
        public string Memo
        {
            get
            {
                return this._Memo;
            }
            set
            {
                this.OnMemoChanging(value);
                this._Memo = value;
                this.OnMemoChanged();
                this.OnPropertyChanged("Memo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private string _Memo;
        partial void OnMemoChanging(string value);
        partial void OnMemoChanged();
        /// <summary>
        /// There are no comments for Property Bit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Bit")]
        public global::System.Nullable<bool> Bit
        {
            get
            {
                return this._Bit;
            }
            set
            {
                this.OnBitChanging(value);
                this._Bit = value;
                this.OnBitChanged();
                this.OnPropertyChanged("Bit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::System.Nullable<bool> _Bit;
        partial void OnBitChanging(global::System.Nullable<bool> value);
        partial void OnBitChanged();
        /// <summary>
        /// There are no comments for Property TinyInt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TinyInt")]
        public global::System.Nullable<byte> TinyInt
        {
            get
            {
                return this._TinyInt;
            }
            set
            {
                this.OnTinyIntChanging(value);
                this._TinyInt = value;
                this.OnTinyIntChanged();
                this.OnPropertyChanged("TinyInt");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::System.Nullable<byte> _TinyInt;
        partial void OnTinyIntChanging(global::System.Nullable<byte> value);
        partial void OnTinyIntChanged();
        /// <summary>
        /// There are no comments for Property SmallInt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("SmallInt")]
        public global::System.Nullable<short> SmallInt
        {
            get
            {
                return this._SmallInt;
            }
            set
            {
                this.OnSmallIntChanging(value);
                this._SmallInt = value;
                this.OnSmallIntChanged();
                this.OnPropertyChanged("SmallInt");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::System.Nullable<short> _SmallInt;
        partial void OnSmallIntChanging(global::System.Nullable<short> value);
        partial void OnSmallIntChanged();
        /// <summary>
        /// There are no comments for Property Int in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Int")]
        public global::System.Nullable<int> Int
        {
            get
            {
                return this._Int;
            }
            set
            {
                this.OnIntChanging(value);
                this._Int = value;
                this.OnIntChanged();
                this.OnPropertyChanged("Int");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::System.Nullable<int> _Int;
        partial void OnIntChanging(global::System.Nullable<int> value);
        partial void OnIntChanged();
        /// <summary>
        /// There are no comments for Property BigInt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BigInt")]
        public global::System.Nullable<long> BigInt
        {
            get
            {
                return this._BigInt;
            }
            set
            {
                this.OnBigIntChanging(value);
                this._BigInt = value;
                this.OnBigIntChanged();
                this.OnPropertyChanged("BigInt");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::System.Nullable<long> _BigInt;
        partial void OnBigIntChanging(global::System.Nullable<long> value);
        partial void OnBigIntChanged();
        /// <summary>
        /// There are no comments for Property SmallMoney in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("SmallMoney")]
        public global::System.Nullable<decimal> SmallMoney
        {
            get
            {
                return this._SmallMoney;
            }
            set
            {
                this.OnSmallMoneyChanging(value);
                this._SmallMoney = value;
                this.OnSmallMoneyChanged();
                this.OnPropertyChanged("SmallMoney");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::System.Nullable<decimal> _SmallMoney;
        partial void OnSmallMoneyChanging(global::System.Nullable<decimal> value);
        partial void OnSmallMoneyChanged();
        /// <summary>
        /// There are no comments for Property Money in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Money")]
        public global::System.Nullable<decimal> Money
        {
            get
            {
                return this._Money;
            }
            set
            {
                this.OnMoneyChanging(value);
                this._Money = value;
                this.OnMoneyChanged();
                this.OnPropertyChanged("Money");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::System.Nullable<decimal> _Money;
        partial void OnMoneyChanging(global::System.Nullable<decimal> value);
        partial void OnMoneyChanged();
        /// <summary>
        /// There are no comments for Property Decimal in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Decimal")]
        public global::System.Nullable<decimal> Decimal
        {
            get
            {
                return this._Decimal;
            }
            set
            {
                this.OnDecimalChanging(value);
                this._Decimal = value;
                this.OnDecimalChanged();
                this.OnPropertyChanged("Decimal");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::System.Nullable<decimal> _Decimal;
        partial void OnDecimalChanging(global::System.Nullable<decimal> value);
        partial void OnDecimalChanged();
        /// <summary>
        /// There are no comments for Property Numeric in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Numeric")]
        public global::System.Nullable<decimal> Numeric
        {
            get
            {
                return this._Numeric;
            }
            set
            {
                this.OnNumericChanging(value);
                this._Numeric = value;
                this.OnNumericChanged();
                this.OnPropertyChanged("Numeric");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::System.Nullable<decimal> _Numeric;
        partial void OnNumericChanging(global::System.Nullable<decimal> value);
        partial void OnNumericChanged();
        /// <summary>
        /// There are no comments for Property Numeric5 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Numeric5")]
        public global::System.Nullable<decimal> Numeric5
        {
            get
            {
                return this._Numeric5;
            }
            set
            {
                this.OnNumeric5Changing(value);
                this._Numeric5 = value;
                this.OnNumeric5Changed();
                this.OnPropertyChanged("Numeric5");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::System.Nullable<decimal> _Numeric5;
        partial void OnNumeric5Changing(global::System.Nullable<decimal> value);
        partial void OnNumeric5Changed();
        /// <summary>
        /// There are no comments for Property Numeric9 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Numeric9")]
        public global::System.Nullable<decimal> Numeric9
        {
            get
            {
                return this._Numeric9;
            }
            set
            {
                this.OnNumeric9Changing(value);
                this._Numeric9 = value;
                this.OnNumeric9Changed();
                this.OnPropertyChanged("Numeric9");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::System.Nullable<decimal> _Numeric9;
        partial void OnNumeric9Changing(global::System.Nullable<decimal> value);
        partial void OnNumeric9Changed();
        /// <summary>
        /// There are no comments for Property Numeric13 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Numeric13")]
        public global::System.Nullable<decimal> Numeric13
        {
            get
            {
                return this._Numeric13;
            }
            set
            {
                this.OnNumeric13Changing(value);
                this._Numeric13 = value;
                this.OnNumeric13Changed();
                this.OnPropertyChanged("Numeric13");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::System.Nullable<decimal> _Numeric13;
        partial void OnNumeric13Changing(global::System.Nullable<decimal> value);
        partial void OnNumeric13Changed();
        /// <summary>
        /// There are no comments for Property Numeric17 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Numeric17")]
        public global::System.Nullable<decimal> Numeric17
        {
            get
            {
                return this._Numeric17;
            }
            set
            {
                this.OnNumeric17Changing(value);
                this._Numeric17 = value;
                this.OnNumeric17Changed();
                this.OnPropertyChanged("Numeric17");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::System.Nullable<decimal> _Numeric17;
        partial void OnNumeric17Changing(global::System.Nullable<decimal> value);
        partial void OnNumeric17Changed();
        /// <summary>
        /// There are no comments for Property Real in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Real")]
        public global::System.Nullable<float> Real
        {
            get
            {
                return this._Real;
            }
            set
            {
                this.OnRealChanging(value);
                this._Real = value;
                this.OnRealChanged();
                this.OnPropertyChanged("Real");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::System.Nullable<float> _Real;
        partial void OnRealChanging(global::System.Nullable<float> value);
        partial void OnRealChanged();
        /// <summary>
        /// There are no comments for Property Float in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Float")]
        public global::System.Nullable<double> Float
        {
            get
            {
                return this._Float;
            }
            set
            {
                this.OnFloatChanging(value);
                this._Float = value;
                this.OnFloatChanged();
                this.OnPropertyChanged("Float");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::System.Nullable<double> _Float;
        partial void OnFloatChanging(global::System.Nullable<double> value);
        partial void OnFloatChanged();
        /// <summary>
        /// There are no comments for Property Time in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Time")]
        public global::System.Nullable<global::System.TimeSpan> Time
        {
            get
            {
                return this._Time;
            }
            set
            {
                this.OnTimeChanging(value);
                this._Time = value;
                this.OnTimeChanged();
                this.OnPropertyChanged("Time");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::System.Nullable<global::System.TimeSpan> _Time;
        partial void OnTimeChanging(global::System.Nullable<global::System.TimeSpan> value);
        partial void OnTimeChanged();
        /// <summary>
        /// There are no comments for Property DateTimeOffset in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DateTimeOffset")]
        public global::System.Nullable<global::System.DateTimeOffset> DateTimeOffset
        {
            get
            {
                return this._DateTimeOffset;
            }
            set
            {
                this.OnDateTimeOffsetChanging(value);
                this._DateTimeOffset = value;
                this.OnDateTimeOffsetChanged();
                this.OnPropertyChanged("DateTimeOffset");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _DateTimeOffset;
        partial void OnDateTimeOffsetChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDateTimeOffsetChanged();
        /// <summary>
        /// There are no comments for Property Char10 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Char10")]
        public string Char10
        {
            get
            {
                return this._Char10;
            }
            set
            {
                this.OnChar10Changing(value);
                this._Char10 = value;
                this.OnChar10Changed();
                this.OnPropertyChanged("Char10");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private string _Char10;
        partial void OnChar10Changing(string value);
        partial void OnChar10Changed();
        /// <summary>
        /// There are no comments for Property VarChar50 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("VarChar50")]
        public string VarChar50
        {
            get
            {
                return this._VarChar50;
            }
            set
            {
                this.OnVarChar50Changing(value);
                this._VarChar50 = value;
                this.OnVarChar50Changed();
                this.OnPropertyChanged("VarChar50");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private string _VarChar50;
        partial void OnVarChar50Changing(string value);
        partial void OnVarChar50Changed();
        /// <summary>
        /// There are no comments for Property VarCharMax in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("VarCharMax")]
        public string VarCharMax
        {
            get
            {
                return this._VarCharMax;
            }
            set
            {
                this.OnVarCharMaxChanging(value);
                this._VarCharMax = value;
                this.OnVarCharMaxChanged();
                this.OnPropertyChanged("VarCharMax");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private string _VarCharMax;
        partial void OnVarCharMaxChanging(string value);
        partial void OnVarCharMaxChanged();
        /// <summary>
        /// There are no comments for Property Text in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Text")]
        public string Text
        {
            get
            {
                return this._Text;
            }
            set
            {
                this.OnTextChanging(value);
                this._Text = value;
                this.OnTextChanged();
                this.OnPropertyChanged("Text");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private string _Text;
        partial void OnTextChanging(string value);
        partial void OnTextChanged();
        /// <summary>
        /// There are no comments for Property NChar10 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("NChar10")]
        public string NChar10
        {
            get
            {
                return this._NChar10;
            }
            set
            {
                this.OnNChar10Changing(value);
                this._NChar10 = value;
                this.OnNChar10Changed();
                this.OnPropertyChanged("NChar10");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private string _NChar10;
        partial void OnNChar10Changing(string value);
        partial void OnNChar10Changed();
        /// <summary>
        /// There are no comments for Property NVarChar50 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("NVarChar50")]
        public string NVarChar50
        {
            get
            {
                return this._NVarChar50;
            }
            set
            {
                this.OnNVarChar50Changing(value);
                this._NVarChar50 = value;
                this.OnNVarChar50Changed();
                this.OnPropertyChanged("NVarChar50");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private string _NVarChar50;
        partial void OnNVarChar50Changing(string value);
        partial void OnNVarChar50Changed();
        /// <summary>
        /// There are no comments for Property NVarCharMax in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("NVarCharMax")]
        public string NVarCharMax
        {
            get
            {
                return this._NVarCharMax;
            }
            set
            {
                this.OnNVarCharMaxChanging(value);
                this._NVarCharMax = value;
                this.OnNVarCharMaxChanged();
                this.OnPropertyChanged("NVarCharMax");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private string _NVarCharMax;
        partial void OnNVarCharMaxChanging(string value);
        partial void OnNVarCharMaxChanged();
        /// <summary>
        /// There are no comments for Property NText in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("NText")]
        public string NText
        {
            get
            {
                return this._NText;
            }
            set
            {
                this.OnNTextChanging(value);
                this._NText = value;
                this.OnNTextChanged();
                this.OnPropertyChanged("NText");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private string _NText;
        partial void OnNTextChanging(string value);
        partial void OnNTextChanged();
        /// <summary>
        /// There are no comments for Property Binary in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Binary")]
        public byte[] Binary
        {
            get
            {
                return this._Binary;
            }
            set
            {
                this.OnBinaryChanging(value);
                this._Binary = value;
                this.OnBinaryChanged();
                this.OnPropertyChanged("Binary");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private byte[] _Binary;
        partial void OnBinaryChanging(byte[] value);
        partial void OnBinaryChanged();
        /// <summary>
        /// There are no comments for Property VarBinary in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("VarBinary")]
        public byte[] VarBinary
        {
            get
            {
                return this._VarBinary;
            }
            set
            {
                this.OnVarBinaryChanging(value);
                this._VarBinary = value;
                this.OnVarBinaryChanged();
                this.OnPropertyChanged("VarBinary");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private byte[] _VarBinary;
        partial void OnVarBinaryChanging(byte[] value);
        partial void OnVarBinaryChanged();
        /// <summary>
        /// There are no comments for Property VarBinaryMax in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("VarBinaryMax")]
        public byte[] VarBinaryMax
        {
            get
            {
                return this._VarBinaryMax;
            }
            set
            {
                this.OnVarBinaryMaxChanging(value);
                this._VarBinaryMax = value;
                this.OnVarBinaryMaxChanged();
                this.OnPropertyChanged("VarBinaryMax");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private byte[] _VarBinaryMax;
        partial void OnVarBinaryMaxChanging(byte[] value);
        partial void OnVarBinaryMaxChanged();
        /// <summary>
        /// There are no comments for Property Image in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Image")]
        public byte[] Image
        {
            get
            {
                return this._Image;
            }
            set
            {
                this.OnImageChanging(value);
                this._Image = value;
                this.OnImageChanged();
                this.OnPropertyChanged("Image");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private byte[] _Image;
        partial void OnImageChanging(byte[] value);
        partial void OnImageChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("RowVersion")]
        public byte[] RowVersion
        {
            get
            {
                return this._RowVersion;
            }
            set
            {
                this.OnRowVersionChanging(value);
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Property Xml in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Xml")]
        public string Xml
        {
            get
            {
                return this._Xml;
            }
            set
            {
                this.OnXmlChanging(value);
                this._Xml = value;
                this.OnXmlChanged();
                this.OnPropertyChanged("Xml");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private string _Xml;
        partial void OnXmlChanging(string value);
        partial void OnXmlChanged();
        /// <summary>
        /// There are no comments for Property Geometry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Geometry")]
        public global::KendoUI.Models.System.Data.Entity.Spatial.DbGeometry Geometry
        {
            get
            {
                return this._Geometry;
            }
            set
            {
                this.OnGeometryChanging(value);
                this._Geometry = value;
                this.OnGeometryChanged();
                this.OnPropertyChanged("Geometry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::KendoUI.Models.System.Data.Entity.Spatial.DbGeometry _Geometry;
        partial void OnGeometryChanging(global::KendoUI.Models.System.Data.Entity.Spatial.DbGeometry value);
        partial void OnGeometryChanged();
        /// <summary>
        /// There are no comments for Property Geography in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Geography")]
        public global::KendoUI.Models.System.Data.Entity.Spatial.DbGeography Geography
        {
            get
            {
                return this._Geography;
            }
            set
            {
                this.OnGeographyChanging(value);
                this._Geography = value;
                this.OnGeographyChanged();
                this.OnPropertyChanged("Geography");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::KendoUI.Models.System.Data.Entity.Spatial.DbGeography _Geography;
        partial void OnGeographyChanging(global::KendoUI.Models.System.Data.Entity.Spatial.DbGeography value);
        partial void OnGeographyChanged();
        /// <summary>
        /// There are no comments for Property Category in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Category")]
        public global::KendoUI.Models.OData.Models.Category Category
        {
            get
            {
                return this._Category;
            }
            set
            {
                this.OnCategoryChanging(value);
                this._Category = value;
                this.OnCategoryChanged();
                this.OnPropertyChanged("Category");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::KendoUI.Models.OData.Models.Category _Category;
        partial void OnCategoryChanging(global::KendoUI.Models.OData.Models.Category value);
        partial void OnCategoryChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::KendoUI.Models.OData.Models.Category as global::KendoUI.Models.OData.Models.CategorySingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::KendoUI.Models.OData.Models.CategorySingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::KendoUI.Models.OData.Models.Category> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::KendoUI.Models.OData.Models.CategorySingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::KendoUI.Models.OData.Models.Category as global::KendoUI.Models.OData.Models.CategorySingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="iD">The value of iD</param>
        public static global::KendoUI.Models.OData.Models.CategorySingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::KendoUI.Models.OData.Models.Category> source,
            int iD)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "ID", iD }
            };
            return new global::KendoUI.Models.OData.Models.CategorySingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::KendoUI.Models.OData.Models.Product as global::KendoUI.Models.OData.Models.ProductSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::KendoUI.Models.OData.Models.ProductSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::KendoUI.Models.OData.Models.Product> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::KendoUI.Models.OData.Models.ProductSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::KendoUI.Models.OData.Models.Product as global::KendoUI.Models.OData.Models.ProductSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="iD">The value of iD</param>
        public static global::KendoUI.Models.OData.Models.ProductSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::KendoUI.Models.OData.Models.Product> source,
            global::System.Guid iD)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "ID", iD }
            };
            return new global::KendoUI.Models.OData.Models.ProductSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace KendoUI.Models.System.Data.Entity.Spatial
{
    /// <summary>
    /// There are no comments for DbGeometry in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("DbGeometry")]
    public partial class DbGeometry : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property Geometry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Geometry")]
        public global::KendoUI.Models.System.Data.Entity.Spatial.DbGeometryWellKnownValue Geometry
        {
            get
            {
                return this._Geometry;
            }
            set
            {
                this.OnGeometryChanging(value);
                this._Geometry = value;
                this.OnGeometryChanged();
                this.OnPropertyChanged("Geometry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::KendoUI.Models.System.Data.Entity.Spatial.DbGeometryWellKnownValue _Geometry;
        partial void OnGeometryChanging(global::KendoUI.Models.System.Data.Entity.Spatial.DbGeometryWellKnownValue value);
        partial void OnGeometryChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for DbGeometryWellKnownValue in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("DbGeometryWellKnownValue")]
    public partial class DbGeometryWellKnownValue : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property CoordinateSystemId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CoordinateSystemId")]
        public global::System.Nullable<int> CoordinateSystemId
        {
            get
            {
                return this._CoordinateSystemId;
            }
            set
            {
                this.OnCoordinateSystemIdChanging(value);
                this._CoordinateSystemId = value;
                this.OnCoordinateSystemIdChanged();
                this.OnPropertyChanged("CoordinateSystemId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::System.Nullable<int> _CoordinateSystemId;
        partial void OnCoordinateSystemIdChanging(global::System.Nullable<int> value);
        partial void OnCoordinateSystemIdChanged();
        /// <summary>
        /// There are no comments for Property WellKnownText in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("WellKnownText")]
        public string WellKnownText
        {
            get
            {
                return this._WellKnownText;
            }
            set
            {
                this.OnWellKnownTextChanging(value);
                this._WellKnownText = value;
                this.OnWellKnownTextChanged();
                this.OnPropertyChanged("WellKnownText");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private string _WellKnownText;
        partial void OnWellKnownTextChanging(string value);
        partial void OnWellKnownTextChanged();
        /// <summary>
        /// There are no comments for Property WellKnownBinary in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("WellKnownBinary")]
        public byte[] WellKnownBinary
        {
            get
            {
                return this._WellKnownBinary;
            }
            set
            {
                this.OnWellKnownBinaryChanging(value);
                this._WellKnownBinary = value;
                this.OnWellKnownBinaryChanged();
                this.OnPropertyChanged("WellKnownBinary");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private byte[] _WellKnownBinary;
        partial void OnWellKnownBinaryChanging(byte[] value);
        partial void OnWellKnownBinaryChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for DbGeography in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("DbGeography")]
    public partial class DbGeography : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property Geography in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Geography")]
        public global::KendoUI.Models.System.Data.Entity.Spatial.DbGeographyWellKnownValue Geography
        {
            get
            {
                return this._Geography;
            }
            set
            {
                this.OnGeographyChanging(value);
                this._Geography = value;
                this.OnGeographyChanged();
                this.OnPropertyChanged("Geography");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::KendoUI.Models.System.Data.Entity.Spatial.DbGeographyWellKnownValue _Geography;
        partial void OnGeographyChanging(global::KendoUI.Models.System.Data.Entity.Spatial.DbGeographyWellKnownValue value);
        partial void OnGeographyChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for DbGeographyWellKnownValue in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("DbGeographyWellKnownValue")]
    public partial class DbGeographyWellKnownValue : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property CoordinateSystemId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CoordinateSystemId")]
        public global::System.Nullable<int> CoordinateSystemId
        {
            get
            {
                return this._CoordinateSystemId;
            }
            set
            {
                this.OnCoordinateSystemIdChanging(value);
                this._CoordinateSystemId = value;
                this.OnCoordinateSystemIdChanged();
                this.OnPropertyChanged("CoordinateSystemId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::System.Nullable<int> _CoordinateSystemId;
        partial void OnCoordinateSystemIdChanging(global::System.Nullable<int> value);
        partial void OnCoordinateSystemIdChanged();
        /// <summary>
        /// There are no comments for Property WellKnownText in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("WellKnownText")]
        public string WellKnownText
        {
            get
            {
                return this._WellKnownText;
            }
            set
            {
                this.OnWellKnownTextChanging(value);
                this._WellKnownText = value;
                this.OnWellKnownTextChanged();
                this.OnPropertyChanged("WellKnownText");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private string _WellKnownText;
        partial void OnWellKnownTextChanging(string value);
        partial void OnWellKnownTextChanged();
        /// <summary>
        /// There are no comments for Property WellKnownBinary in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("WellKnownBinary")]
        public byte[] WellKnownBinary
        {
            get
            {
                return this._WellKnownBinary;
            }
            set
            {
                this.OnWellKnownBinaryChanging(value);
                this._WellKnownBinary = value;
                this.OnWellKnownBinaryChanged();
                this.OnPropertyChanged("WellKnownBinary");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private byte[] _WellKnownBinary;
        partial void OnWellKnownBinaryChanging(byte[] value);
        partial void OnWellKnownBinaryChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
namespace KendoUI.Models.Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "System.Data.Entity.Spatial", "KendoUI.Models.System.Data.Entity.Spatial");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "OData.Models", "KendoUI.Models.OData.Models");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "KendoUI.Models.Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("KendoUI.Models.System.Data.Entity.Spatial", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("System.Data.Entity.Spatial.", originalNameAttribute.OriginalName);
                }
                return string.Concat("System.Data.Entity.Spatial.", clientType.Name);
            }
            if (clientType.Namespace.Equals("KendoUI.Models.OData.Models", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("OData.Models.", originalNameAttribute.OriginalName);
                }
                return string.Concat("OData.Models.", clientType.Name);
            }
            if (clientType.Namespace.Equals("KendoUI.Models.Default", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Default.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Default.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Categories in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::KendoUI.Models.OData.Models.Category> Categories
        {
            get
            {
                if ((this._Categories == null))
                {
                    this._Categories = base.CreateQuery<global::KendoUI.Models.OData.Models.Category>("Categories");
                }
                return this._Categories;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::KendoUI.Models.OData.Models.Category> _Categories;
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::KendoUI.Models.OData.Models.Product> Products
        {
            get
            {
                if ((this._Products == null))
                {
                    this._Products = base.CreateQuery<global::KendoUI.Models.OData.Models.Product>("Products");
                }
                return this._Products;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::KendoUI.Models.OData.Models.Product> _Products;
        /// <summary>
        /// There are no comments for Categories in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        public void AddToCategories(global::KendoUI.Models.OData.Models.Category category)
        {
            base.AddObject("Categories", category);
        }
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        public void AddToProducts(global::KendoUI.Models.OData.Models.Product product)
        {
            base.AddObject("Products", product);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""OData.Models"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Category"">
        <Key>
          <PropertyRef Name=""ID"" />
        </Key>
        <Property Name=""ID"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" Nullable=""false"" />
      </EntityType>
      <EntityType Name=""Product"">
        <Key>
          <PropertyRef Name=""ID"" />
        </Key>
        <Property Name=""UnitPrice"" Type=""Edm.Decimal"" />
        <Property Name=""Date"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""SmallDateTime"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""DateTime"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""DateTime2"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""ID"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""CurrencyID"" Type=""Edm.Int16"" />
        <Property Name=""CategoryID"" Type=""Edm.Int32"" />
        <Property Name=""Description"" Type=""Edm.String"" />
        <Property Name=""IntroductionUrl"" Type=""Edm.String"" />
        <Property Name=""ImageUrl"" Type=""Edm.String"" />
        <Property Name=""Memo"" Type=""Edm.String"" />
        <Property Name=""Bit"" Type=""Edm.Boolean"" />
        <Property Name=""TinyInt"" Type=""Edm.Byte"" />
        <Property Name=""SmallInt"" Type=""Edm.Int16"" />
        <Property Name=""Int"" Type=""Edm.Int32"" />
        <Property Name=""BigInt"" Type=""Edm.Int64"" />
        <Property Name=""SmallMoney"" Type=""Edm.Decimal"" />
        <Property Name=""Money"" Type=""Edm.Decimal"" />
        <Property Name=""Decimal"" Type=""Edm.Decimal"" />
        <Property Name=""Numeric"" Type=""Edm.Decimal"" />
        <Property Name=""Numeric5"" Type=""Edm.Decimal"" />
        <Property Name=""Numeric9"" Type=""Edm.Decimal"" />
        <Property Name=""Numeric13"" Type=""Edm.Decimal"" />
        <Property Name=""Numeric17"" Type=""Edm.Decimal"" />
        <Property Name=""Real"" Type=""Edm.Single"" />
        <Property Name=""Float"" Type=""Edm.Double"" />
        <Property Name=""Time"" Type=""Edm.Duration"" />
        <Property Name=""DateTimeOffset"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""Char10"" Type=""Edm.String"" />
        <Property Name=""VarChar50"" Type=""Edm.String"" />
        <Property Name=""VarCharMax"" Type=""Edm.String"" />
        <Property Name=""Text"" Type=""Edm.String"" />
        <Property Name=""NChar10"" Type=""Edm.String"" />
        <Property Name=""NVarChar50"" Type=""Edm.String"" />
        <Property Name=""NVarCharMax"" Type=""Edm.String"" />
        <Property Name=""NText"" Type=""Edm.String"" />
        <Property Name=""Binary"" Type=""Edm.Binary"" />
        <Property Name=""VarBinary"" Type=""Edm.Binary"" />
        <Property Name=""VarBinaryMax"" Type=""Edm.Binary"" />
        <Property Name=""Image"" Type=""Edm.Binary"" />
        <Property Name=""RowVersion"" Type=""Edm.Binary"" ConcurrencyMode=""Fixed"" />
        <Property Name=""Xml"" Type=""Edm.String"" />
        <Property Name=""Geometry"" Type=""System.Data.Entity.Spatial.DbGeometry"" />
        <Property Name=""Geography"" Type=""System.Data.Entity.Spatial.DbGeography"" />
        <NavigationProperty Name=""Category"" Type=""OData.Models.Category"" />
      </EntityType>
    </Schema>
    <Schema Namespace=""System.Data.Entity.Spatial"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <ComplexType Name=""DbGeometry"">
        <Property Name=""Geometry"" Type=""System.Data.Entity.Spatial.DbGeometryWellKnownValue"" />
      </ComplexType>
      <ComplexType Name=""DbGeometryWellKnownValue"">
        <Property Name=""CoordinateSystemId"" Type=""Edm.Int32"" />
        <Property Name=""WellKnownText"" Type=""Edm.String"" />
        <Property Name=""WellKnownBinary"" Type=""Edm.Binary"" />
      </ComplexType>
      <ComplexType Name=""DbGeography"">
        <Property Name=""Geography"" Type=""System.Data.Entity.Spatial.DbGeographyWellKnownValue"" />
      </ComplexType>
      <ComplexType Name=""DbGeographyWellKnownValue"">
        <Property Name=""CoordinateSystemId"" Type=""Edm.Int32"" />
        <Property Name=""WellKnownText"" Type=""Edm.String"" />
        <Property Name=""WellKnownBinary"" Type=""Edm.Binary"" />
      </ComplexType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""Container"">
        <EntitySet Name=""Categories"" EntityType=""OData.Models.Category"" />
        <EntitySet Name=""Products"" EntityType=""OData.Models.Product"">
          <NavigationPropertyBinding Path=""Category"" Target=""Categories"" />
        </EntitySet>
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.1.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
