//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoUI.Views.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewModelResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KendoUI.Views.App_LocalResources.ViewModelResource", typeof(ViewModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 分类说明。 的本地化字符串。
        /// </summary>
        public static string Category_Description {
            get {
                return ResourceManager.GetString("Category_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类 的本地化字符串。
        /// </summary>
        public static string Category_Name {
            get {
                return ResourceManager.GetString("Category_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类提示。 的本地化字符串。
        /// </summary>
        public static string Category_Prompt {
            get {
                return ResourceManager.GetString("Category_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类1 的本地化字符串。
        /// </summary>
        public static string Category_ShortName {
            get {
                return ResourceManager.GetString("Category_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动编号说明。 的本地化字符串。
        /// </summary>
        public static string ID_Description {
            get {
                return ResourceManager.GetString("ID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动编号 的本地化字符串。
        /// </summary>
        public static string ID_Name {
            get {
                return ResourceManager.GetString("ID_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动编号提示。 的本地化字符串。
        /// </summary>
        public static string ID_Prompt {
            get {
                return ResourceManager.GetString("ID_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号 的本地化字符串。
        /// </summary>
        public static string ID_ShortName {
            get {
                return ResourceManager.GetString("ID_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称说明。 的本地化字符串。
        /// </summary>
        public static string Name_Description {
            get {
                return ResourceManager.GetString("Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string Name_Name {
            get {
                return ResourceManager.GetString("Name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称提示。 的本地化字符串。
        /// </summary>
        public static string Name_Prompt {
            get {
                return ResourceManager.GetString("Name_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称1 的本地化字符串。
        /// </summary>
        public static string Name_ShortName {
            get {
                return ResourceManager.GetString("Name_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 价格说明。 的本地化字符串。
        /// </summary>
        public static string Price_Description {
            get {
                return ResourceManager.GetString("Price_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 价格 的本地化字符串。
        /// </summary>
        public static string Price_Name {
            get {
                return ResourceManager.GetString("Price_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 价格提示。 的本地化字符串。
        /// </summary>
        public static string Price_Prompt {
            get {
                return ResourceManager.GetString("Price_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 价格1 的本地化字符串。
        /// </summary>
        public static string Price_ShortName {
            get {
                return ResourceManager.GetString("Price_ShortName", resourceCulture);
            }
        }
    }
}
